# leetcode-python
每天刷LeetCode~~~

001：
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
//给定两个字符串s和t只包含小写字母。字符串t是由随机洗牌字符串s,然后再添加一个字母在一个随机位置。在t找到添加的字符。
>>>解决：
    class Solution:
        def findTheDifference(self, s, t):
            """
            :type s: str
            :type t: str
            :rtype: str
            """
            for t_each in t:
                if t_each not in s:
                    return t_each
                else:
                    if s.count(t_each)!=t.count(t_each):
                        return t_each
>>>重新洗牌排序只能保证元素的个数和原始相当的情况下次元素不属于新添加元素，若元素不存在于s字符中也表明此字符属于新添加字符;
>>>最优解：
def findTheDifference(self, s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    ans = 0
    for c in s + t:
        ans ^= ord(c)
    return chr(ans)
>>>ord(x)函数是将x转换为相应的AscII码 是一个数字，chr（x）则将数字或16进制字符转换为字符串
